### ISSUE TITLE
check content of owiNrcs_no_noise_correction var 

### ISSUE THREAD

**Issue by vincelhx** [umr-lops/grdwindinversion#48]

**Comment by agrouaze** [comment]
Hello @vincelhx ,
This issue cas a typo or the variable names were not clear enough? I remember that at some point we used the "co-GMF" for cross channels inversion because the "cross-GMF" was not available. It is a related problem?
BTW I prefer that we always go through pull request, even for very small modifications like this. It is much easier then when you want to track the differences between releases.

**Comment by vincelhx** [comment]
Hi @agrouaze 

I grdwindinversion, i (wrongly) recreated `owiNrcs_no_noise_correction` or `owiNrcs_cross_no_noise_correction` but it was already in L1-products with `sigma0_raw` var. 
What we did for HH/HV products is that we temporarly use VV/VH GMFs. but it's unrelated.

Ok, i will now use a fork
